on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_cvs:
    runs-on: ubuntu-22.04
    name: "Generate .pdf/.html CVs"
    env:
      DOC_BASENAME: "Saheed-Adeleye"
      CV_DIR: "main"
      WEBSITE_DIR: "website"
      pdfname: "Saheed-Adeleye.pdf"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the CV sources
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout the website sources
        uses: actions/checkout@v4
        with:
          repository: gyreas/gyreas.github.io
          path: website

      - name: Install typst
        run: |
          sudo snap install typst
          echo "PWD=$PWD"
          tree

      - name: Compile .pdf document
        run: |
          cd "$CV_DIR"
          typst compile --format pdf main.typ "$pdfname"
          ls -lh

      - name: Copy to website and push
        run: |
          cp --verbose "$CV_DIR/$pdfname" "$WEBSITE_DIR/assets"

          cd "$WEBSITE_DIR"
          date > generated.txt

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "assets/$pdfname" generated.txt
          git commit -m "Updated CV PDF: [bot-$(date)]"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/gyreas/gyreas.github.io.git
          git push
