on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  generate_cvs:
    runs-on: ubuntu-22.04
    name: "Generate .pdf/.html CVs"
    steps:
      - name: Checkout the CV sources
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout the website sources
        uses: actions/checkout@v4
        with:
          repository: gyreas/gyreas.github.io
          path: website
 
      - name: Install deps
        run: |
          sudo snap install typst
          
          echo "PWD="$PWD
          ls -hl
          tree
         
      - name: Compile .pdf document
        run: |
          cd $CV_DIR
          typst compile --format pdf main.typ $pdfname

      - name: Upload the documents to my website
        run: |
          ls -hl
          tree
          cp --verbose "$CV_DIR/$pdfname" "$WEBSITE_DIR/assets"
          cd $WEBSITE_DIR
          git add "assets/$pdfname"
          git commit -m "updated CV [pdf]" "assets/$pdfname"
          git push
                 
    env:
      pdfname: "$DOC_BASENAME.pdf"
      DOC_BASENAME: "Saheed-Adeleye"
      CV_DIR: "main"
      WEBSITE_DIR: "website"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
