on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  generate_cvs:
    runs-on: ubuntu-22.04
    name: "Generate .pdf/.html CVs"
    steps:
      - name: Checkout the CV sources
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout the website sources
        uses: actions/checkout@v4
        with:
          repository: gyreas/gyreas.github.io
          path: website

      - name: generate
        run: |
          sudo apt install gh git; sudo snap install typst
          mkdir ~/bin; curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          echo "PWD=" $PWD; ls -hl; tree;
          ~/bin/just --justfile Justfile
  
        env:
          CV_DIR: "main/"
          WEBSITE_DIR: "website/"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
