on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  generate_cvs:
    runs-on: ubuntu-22.04
    name: "Generate .pdf/.html CVs"
    steps:
      - name: "generate via just"
        run: |
          sudo apt install gh git
          sudo snap install typst
          mkdir ~/bin
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          pwd
          echo "PWD=" $PWD; ls -hl; ~/bin/just --justfile Justfile
